server:
  port: ${port:8080}
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Review
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql:true
        format_sql:true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging.level:
  org.hibernate.SQL: debug
